//! FOC controller — mode dispatch over the cascade (off / torque / speed / position).
//!
//! ## Modes
//!
//! | Mode       | Active chain                                 | `target.*` field used |
//! |------------|----------------------------------------------|------------------------|
//! | `Off`      | none — no loop runs, duty stays at zero     | (none)                 |
//! | `Torque`   | current loop only                            | `target.iq`            |
//! | `Speed`    | speed loop → current loop                    | `target.speed_ref`     |
//! | `Position` | position loop → speed loop → current loop    | `target.position`      |
//!
//! The current loop is **never** exposed directly.  In `Torque` mode, the
//! user supplies the Iq setpoint; otherwise Iq is generated by an outer loop.
//!
//! The default mode is `Off` — the controller does nothing until the
//! application explicitly switches it on.
//!
//! ## Field layers
//!
//! | Layer | Type | Owner |
//! |-------|------|-------|
//! | `mode` | [`Mode`] | application sets once at start, can change at runtime |
//! | `target` | [`ModeTarget`] | application writes per cycle |
//! | `meas` | [`CascadeMeasurements`] | application writes per cycle |
//! | `position`, `speed`, `current` | inner controllers | composed, accessed for tuning |
//! | `runtime` | [`CascadeRuntime`] | controller writes per cycle (debug) |
//!
//! ## Usage
//!
//! ```ignore
//! let mut ctrl = FocController::new(Mode::Speed);
//! ctrl.speed.feedforward.inertia_gain = 0.001;
//!
//! loop {
//!     ctrl.target.speed_ref = setpoint;
//!     ctrl.meas.speed = encoder.speed();
//!     ctrl.meas.accel = encoder.acceleration();
//!     ctrl.meas.ia = adc.read_a();
//!     ctrl.meas.ib = adc.read_b();
//!     ctrl.meas.theta = encoder.angle();
//!     ctrl.meas.vdc = bus_voltage;
//!
//!     ctrl.update::<LibmTrig>(dt);
//!     pwm.set(ctrl.current.duty);
//! }
//! ```

use crate::current_loop_controller::CurrentLoopController;
use crate::pid::Pid;
use crate::speed_loop_controller::SpeedLoopController;
use crate::transforms::Trig;

/// Control mode.
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Mode {
    /// No loop runs.  Duty stays at zero (motor coasting).
    Off,
    /// Current loop only — user supplies Iq directly.
    Torque,
    /// Speed loop → current loop.
    Speed,
    /// Position loop → speed loop → current loop.
    Position,
}

impl Default for Mode {
    fn default() -> Self { Mode::Off }
}

/// Mode-specific reference inputs.  Only the field matching `mode` is read.
#[derive(Default, Clone, Copy)]
pub struct ModeTarget {
    /// Torque mode: Iq setpoint (A).
    pub iq: f32,
    /// Speed mode: speed setpoint (rad/s).
    pub speed_ref: f32,
    /// Position mode: position setpoint (rad).
    pub position: f32,
    /// Id reference (used in all active modes for flux control / weakening).
    pub id_ref: f32,
}

/// All sensor inputs collected at one place.
#[derive(Default, Clone, Copy)]
pub struct CascadeMeasurements {
    pub position: f32,
    pub speed: f32,
    pub accel: f32,
    pub ia: f32,
    pub ib: f32,
    pub theta: f32,
    pub vdc: f32,
}

/// Aggregated runtime values for logging.
#[derive(Default, Clone, Copy)]
pub struct CascadeRuntime {
    /// Iq target sent into the current loop.
    pub iq_target: f32,
    /// Speed target after position loop, if any.
    pub speed_target: f32,
    pub id_measured: f32,
    pub iq_measured: f32,
    pub vd: f32,
    pub vq: f32,
}

/// Position loop — simple P-only controller (extensible to PID later).
///
/// `omega_target = kp × (position_ref − position_measured)`
///
/// Lives inside `FocController`, but is only used when `mode == Position`.
pub struct PositionController {
    pub kp: f32,
    pub output_limit: f32,
    pub integral: f32,
    pub ki: f32,
    pub prev_measurement: Option<f32>,
}

impl Default for PositionController {
    fn default() -> Self {
        Self { kp: 0.0, ki: 0.0, output_limit: 100.0, integral: 0.0, prev_measurement: None }
    }
}

impl PositionController {
    /// One step.  Returns the speed setpoint.
    pub fn update(&mut self, setpoint: f32, measurement: f32, dt: f32) -> f32 {
        let error = setpoint - measurement;
        let p = self.kp * error;
        // Light I term to remove steady-state position error.
        if p.abs() < self.output_limit {
            self.integral += self.ki * error * dt;
        }
        let out = p + self.integral;
        out.clamp(-self.output_limit, self.output_limit)
    }

    pub fn reset(&mut self) {
        self.integral = 0.0;
        self.prev_measurement = None;
    }
}

/// FOC controller with mode dispatch.
pub struct FocController {
    pub mode: Mode,
    pub target: ModeTarget,
    pub meas: CascadeMeasurements,

    /// Outer loops (only the one matching `mode` runs each cycle).
    pub position: PositionController,
    pub speed: SpeedLoopController,

    /// Inner loop — runs whenever `mode != Off`.  Application reads `duty`.
    pub current: CurrentLoopController,

    pub runtime: CascadeRuntime,
}

impl Default for FocController {
    fn default() -> Self {
        Self::new(Mode::Off)
    }
}

impl FocController {
    pub fn new(mode: Mode) -> Self {
        Self {
            mode,
            target: ModeTarget::default(),
            meas: CascadeMeasurements::default(),
            position: PositionController::default(),
            speed: SpeedLoopController::default(),
            current: CurrentLoopController::default(),
            runtime: CascadeRuntime::default(),
        }
    }

    /// Run one control cycle.
    pub fn update<T: Trig>(&mut self, dt: f32) {
        // 1. Choose the chain based on mode.
        let iq_target = match self.mode {
            Mode::Off => {
                // Disable output: zero duty, no loops run.
                self.current.duty = crate::svpwm::Duty { ta: 0.0, tb: 0.0, tc: 0.0 };
                self.current.svpwm.duty = self.current.duty;
                self.runtime.iq_target = 0.0;
                self.runtime.speed_target = 0.0;
                return;
            }

            Mode::Torque => {
                self.runtime.speed_target = 0.0;
                self.target.iq
            }

            Mode::Speed => {
                // Speed loop measures speed/accel, produces Iq.
                self.speed.meas.speed = self.meas.speed;
                self.speed.meas.accel = self.meas.accel;
                self.speed.target.speed_ref = self.target.speed_ref;
                self.speed.update(dt);
                self.runtime.speed_target = self.target.speed_ref;
                self.speed.iq_target
            }

            Mode::Position => {
                // Position loop produces a speed reference; speed loop produces Iq.
                let omega_ref = self.position.update(
                    self.target.position,
                    self.meas.position,
                    dt,
                );
                self.runtime.speed_target = omega_ref;
                self.speed.meas.speed = self.meas.speed;
                self.speed.meas.accel = self.meas.accel;
                self.speed.target.speed_ref = omega_ref;
                self.speed.update(dt);
                self.speed.iq_target
            }
        };

        self.runtime.iq_target = iq_target;

        // 2. Run current loop.
        self.current.target.iq = iq_target;
        self.current.target.id = self.target.id_ref;
        self.current.meas.ia = self.meas.ia;
        self.current.meas.ib = self.meas.ib;
        self.current.meas.theta = self.meas.theta;
        self.current.svpwm.vdc = self.meas.vdc;
        self.current.update::<T>(dt);

        // 3. Aggregate debug.
        self.runtime.id_measured = self.current.runtime.id_measured;
        self.runtime.iq_measured = self.current.runtime.iq_measured;
        self.runtime.vd = self.current.runtime.vd;
        self.runtime.vq = self.current.runtime.vq;
    }

    pub fn reset(&mut self) {
        self.position.reset();
        self.speed.reset();
        self.current.reset();
    }

    // Direct PID access for tuning.
    pub fn current_pid_d(&mut self) -> &mut Pid { &mut self.current.pid_d }
    pub fn current_pid_q(&mut self) -> &mut Pid { &mut self.current.pid_q }
    pub fn speed_pid(&mut self) -> &mut Pid { &mut self.speed.pid }
    pub fn position_kp(&mut self) -> &mut f32 { &mut self.position.kp }
    pub fn position_ki(&mut self) -> &mut f32 { &mut self.position.ki }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transforms::LibmTrig;

    fn make_vdc(mode: Mode) -> FocController {
        let mut c = FocController::new(mode);
        c.meas.vdc = 24.0;
        c
    }

    #[test]
    fn off_mode_zero_duty() {
        let mut c = FocController::new(Mode::Off);
        c.meas.vdc = 24.0;
        c.update::<LibmTrig>(0.0001);
        approx(c.current.duty.ta, 0.0);
        approx(c.current.duty.tb, 0.0);
        approx(c.current.duty.tc, 0.0);
        approx(c.runtime.iq_target, 0.0);
    }

    #[test]
    fn default_mode_is_off() {
        let c = FocController::default();
        assert_eq!(c.mode, Mode::Off);
    }

    #[test]
    fn torque_mode_passes_iq_directly() {
        let mut c = make_vdc(Mode::Torque);
        c.target.iq = 1.5;
        c.update::<LibmTrig>(0.0001);
        // No PI running (default kp=0), so current loop's vd=vq=0,
        // SVPWM centred, duty 0.5.
        approx(c.current.duty.ta, 0.5);
        approx(c.runtime.iq_target, 1.5);
    }

    #[test]
    fn speed_mode_runs_speed_loop() {
        let mut c = make_vdc(Mode::Speed);
        c.speed.pid.kp = 1.0;
        c.target.speed_ref = 2.0;
        c.meas.speed = 0.0;
        c.update::<LibmTrig>(0.0001);
        // iq_target = 1.0 × 2.0 = 2.0
        approx(c.runtime.iq_target, 2.0);
    }

    #[test]
    fn position_mode_runs_both_loops() {
        let mut c = make_vdc(Mode::Position);
        c.position.kp = 1.0;
        c.speed.pid.kp = 1.0;
        c.target.position = 1.0;     // 1 rad away
        c.meas.position = 0.0;
        c.meas.speed = 0.0;
        c.update::<LibmTrig>(0.0001);
        // Position: kp_p × 1.0 = 1.0 → ω_ref = 1.0
        // Speed: kp_s × 1.0 = 1.0 → iq_target = 1.0
        approx(c.runtime.speed_target, 1.0);
        approx(c.runtime.iq_target, 1.0);
    }

    #[test]
    fn mode_can_be_switched() {
        let mut c = make_vdc(Mode::Speed);
        c.speed.pid.kp = 1.0;
        c.target.speed_ref = 2.0;
        c.meas.speed = 0.0;
        c.update::<LibmTrig>(0.0001);
        let iq_speed = c.runtime.iq_target;
        approx(iq_speed, 2.0);

        c.mode = Mode::Off;
        c.update::<LibmTrig>(0.0001);
        approx(c.runtime.iq_target, 0.0);
        approx(c.current.duty.ta, 0.0);
    }

    #[test]
    fn feedforward_propagates_through_speed_mode() {
        let mut c = make_vdc(Mode::Speed);
        c.speed.pid.kp = 0.0;
        c.speed.feedforward.inertia_gain = 0.5;
        c.meas.accel = 10.0;
        c.update::<LibmTrig>(0.0001);
        approx(c.runtime.iq_target, 5.0);
    }

    fn approx(a: f32, b: f32) {
        assert!((a - b).abs() < 1e-5, "expected {b}, got {a}");
    }
}